package generic.type.erasure.bridgemethod;

public class MyNode extends Node {

	public MyNode(Integer data) {
		super(data);
	}
	
	// Bridge method generated by the compiler.
	public void setData(Object data) {
		setData((Integer) data);
	}
	
	public void setData(Integer data) {
		System.out.println("MyNode.setData");
		super.setData(data);
	}

}
